Repository sablier-labs/v2-core, pull requests merged in 2023-07, with the labels that each got.

#588 test: polish precompiles tests
  .gitmodules
  test/utils/Precompiles.t.sol
Labels: testing

#589 docs: polish deployments section
  README.md
Labels: documentation

#590 docs: polish security program
  SECURITY.md
Labels: documentation

#591 docs: polish license section
  README.md
Labels: documentation

#592 chore: remove Codecov token
  .github/workflows/ci.yml
  README.md
Labels: testing

#594 refactor: update gas snapshot
  .gas-snapshot
Labels: enhancement

#597 refactor: stringify create2 salts
  script/DeployDeterministicComptroller.s.sol
  script/DeployDeterministicCore.s.sol
  script/DeployDeterministicLockupDynamic.s.sol
  script/DeployDeterministicLockupLinear.s.sol
  script/DeployDeterministicNFTDescriptor.s.sol
Labels: enhancement

#602 refactor: rename deployer to broadcaster
  script/Base.s.sol
  script/DeployComptroller.s.sol
  script/DeployCore.s.sol
  script/DeployDeterministicComptroller.s.sol
  script/DeployDeterministicCore.s.sol
  script/DeployDeterministicLockupDynamic.s.sol
  script/DeployDeterministicLockupLinear.s.sol
  script/DeployDeterministicNFTDescriptor.s.sol
  script/DeployLockupDynamic.s.sol
  script/DeployLockupLinear.s.sol
  script/DeployNFTDescriptor.s.sol
  script/Init.s.sol
  test/utils/Utils.sol
Labels: enhancement, feature

#605 chore: use solhint-community
  package.json
  pnpm-lock.yaml
  src/types/Math.sol
  src/types/Tokens.sol
Labels: dependencies

#609 test: remove duplicate bounds
  test/integration/basic/lockup-linear/create-with-range/createWithRange.tree
  test/integration/fuzz/lockup-linear/createWithRange.t.sol
Labels: testing

#614 chore: say token streaming
  package.json
Labels: documentation

#625 chore: add missing modifier in test_SetFlashFee
  test/integration/concrete/comptroller/set-flash-fee/setFlashFee.t.sol
Labels: testing

#624 Add Contribution info in README.md
  README.md
Labels: documentation

#641 refactor: using Given, When and Then keywords in branching Trees
  test/integration/concrete/comptroller/set-protocol-fee/setProtocolFee.t.sol
  test/integration/concrete/comptroller/set-protocol-fee/setProtocolFee.tree
  test/integration/concrete/comptroller/toggle-flash-asset/toggleFlashAsset.t.sol
  test/integration/concrete/comptroller/toggle-flash-asset/toggleFlashAsset.tree
  test/unit/concrete/adminable/transfer-admin/transferAdmin.t.sol
  test/unit/concrete/adminable/transfer-admin/transferAdmin.tree
  test/unit/concrete/comptroller/set-flash-fee/setFlashFee.t.sol
  test/unit/concrete/comptroller/set-flash-fee/setFlashFee.tree
Labels: testing
