Repository sablier-labs/v2-core, pull requests merged in 2023-12, with the labels that each got.

#735 Remove reduntant updateMetadata in withdrawMaxAndTransfer
  src/abstracts/SablierV2Lockup.sol
  test/utils/Precompiles.sol
Labels: enhancement

#740 docs: guideline for fork testing
  CONTRIBUTING.md
Labels: documentation

#758 build: bump solc to 0.8.23
  CHANGELOG.md
  README.md
  foundry.toml
  package.json
  test/utils/Precompiles.sol
Labels: bug, dependencies

#768 build: install deps in prepack
  package.json
Labels: enhancement
