Repository sablier-labs/v2-core, pull requests merged in 2023-09, with the labels that each got.

#678 test: use "given" instead of "when"
  test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.t.sol
  test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.tree
  test/integration/concrete/lockup-dynamic/withdrawable-amount-of/withdrawableAmountOf.t.sol
  test/integration/concrete/lockup-dynamic/withdrawable-amount-of/withdrawableAmountOf.tree
  test/integration/concrete/lockup-linear/streamed-amount-of/streamedAmountOf.tree
  test/integration/concrete/lockup-linear/withdrawable-amount-of/withdrawableAmountOf.t.sol
  test/integration/concrete/lockup-linear/withdrawable-amount-of/withdrawableAmountOf.tree
  test/integration/concrete/lockup/status-of/statusOf.t.sol
  test/integration/concrete/lockup/status-of/statusOf.tree
  test/integration/concrete/lockup/withdraw-max/withdrawMax.t.sol
  test/integration/concrete/lockup/withdraw-max/withdrawMax.tree
  test/integration/concrete/lockup/withdraw/withdraw.t.sol
  test/integration/concrete/lockup/withdraw/withdraw.tree
  test/integration/fuzz/lockup/withdrawMax.t.sol
  test/integration/shared/lockup/withdrawMax.t.sol
Labels: testing

#681 ci: cache testing contracts
  .github/workflows/ci-deep.yml
  .github/workflows/ci.yml
Labels: testing

#686 feat: emit metadata in `_afterTokenTransfer` hook
  src/abstracts/SablierV2Lockup.sol
  test/fork/LockupDynamic.t.sol
  test/fork/LockupLinear.t.sol
  test/integration/concrete/lockup-dynamic/LockupDynamic.t.sol
  test/integration/concrete/lockup-dynamic/create-with-deltas/createWithDeltas.t.sol
  test/integration/concrete/lockup-dynamic/create-with-deltas/createWithDeltas.tree
  test/integration/concrete/lockup-dynamic/create-with-milestones/createWithMilestones.t.sol
  test/integration/concrete/lockup-dynamic/create-with-milestones/createWithMilestones.tree
  test/integration/concrete/lockup-linear/LockupLinear.t.sol
  test/integration/concrete/lockup-linear/create-with-durations/createWithDurations.t.sol
  test/integration/concrete/lockup-linear/create-with-range/createWithRange.t.sol
  test/integration/concrete/lockup-linear/create-with-range/createWithRange.tree
  test/integration/concrete/lockup/burn/burn.t.sol
  test/integration/concrete/lockup/burn/burn.tree
  test/integration/concrete/lockup/transfer-from/transferFrom.t.sol
  test/integration/concrete/lockup/transfer-from/transferFrom.tree
  test/integration/concrete/lockup/withdraw-max-and-transfer/withdrawMaxAndTransfer.t.sol
  test/integration/concrete/lockup/withdraw-max-and-transfer/withdrawMaxAndTransfer.tree
  test/utils/Precompiles.sol
Labels: enhancement

#688 build: upgrade solidity version to 0.8.21
  .gas-snapshot
  foundry.toml
  script/Base.s.sol
  script/DeployComptroller.s.sol
  script/DeployCore.s.sol
  script/DeployCore2.s.sol
  script/DeployDeterministicComptroller.s.sol
  script/DeployDeterministicCore.s.sol
  script/DeployDeterministicCore2.s.sol
  script/DeployDeterministicLockupDynamic.s.sol
  script/DeployDeterministicLockupLinear.s.sol
  script/DeployLockupDynamic.s.sol
  script/DeployLockupLinear.s.sol
  script/GenerateSVG.s.sol
  script/Init.s.sol
  test/utils/Precompiles.sol
  test/utils/Precompiles.t.sol
Labels: dependencies

#683 refactor: dry-fy functions
  src/SablierV2LockupDynamic.sol
  src/SablierV2LockupLinear.sol
  src/abstracts/SablierV2Lockup.sol
  test/utils/Precompiles.sol
Labels: enhancement

#694 build: remove oz peer deps
  package.json
Labels: dependencies

#693 docs: roll 1.1.0
  CHANGELOG.md
  package.json
Labels: documentation
